version: '3'
services:
  flask:
    build: .docker
    container_name: tweets-api
    volumes:
      - ./app:/app/
    environment:
      - FLASK_APP=/app/src/app.py
    command: flask run --host=0.0.0.0
    ports:
      - 5000:5000
